// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBygO6KCTINfloG9A239KypZ2E_uzkG9Mw',
    appId: '1:582311704833:web:3c10a2995cd6105bf4c300',
    messagingSenderId: '582311704833',
    projectId: 'color-sequence-game',
    authDomain: 'color-sequence-game.firebaseapp.com',
    storageBucket: 'color-sequence-game.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0wW42MKaAqjsS8BWsDgCi2JvEyBrEnR4',
    appId: '1:582311704833:android:72bbb7374693843ef4c300',
    messagingSenderId: '582311704833',
    projectId: 'color-sequence-game',
    storageBucket: 'color-sequence-game.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJx_-iLz4eeG2D3DpGnoDHdKQC9pm2QYU',
    appId: '1:582311704833:ios:60194132a72c1848f4c300',
    messagingSenderId: '582311704833',
    projectId: 'color-sequence-game',
    storageBucket: 'color-sequence-game.appspot.com',
    iosBundleId: 'com.example.colorSequenceGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJx_-iLz4eeG2D3DpGnoDHdKQC9pm2QYU',
    appId: '1:582311704833:ios:a455aa8b916ad4ccf4c300',
    messagingSenderId: '582311704833',
    projectId: 'color-sequence-game',
    storageBucket: 'color-sequence-game.appspot.com',
    iosBundleId: 'com.example.colorSequenceGame.RunnerTests',
  );
}
